CREATE TABLE contatos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(20),
    cidade VARCHAR(50),
    mensagem TEXT NOT NULL,
    criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
